---
# tasks file for lighthouse
- name: Nginx | Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Nginx | Install Nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
- name: Nginx | Create config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Start-nginx

- name: Lighthouse | Install Dependencies
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Create Lighthouse directory
  become: true
  ansible.builtin.file:
    path: /var/www/lighthouse
    state: directory
    recurse: yes
    mode: '0755'
    owner: nginx
    group: nginx
- name: Check if Lighthouse directory exists
  ansible.builtin.stat:
    path: /var/www/lighthouse/.git
  register: lighthouse_repo
- name: Ensure safe.directory is set for lighthouse
  ansible.builtin.shell:
    cmd: "git config --global --add safe.directory /var/www/lighthouse"
    args:
    creates: /var/www/lighthouse/.git
- name: Lighthouse | Clone from Git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: "master"
    dest: "{{ lighthouse_location_dir }}"
    update: false
  when: not lighthouse_repo.stat.exists
  changed_when: false
- name: Lighthouse | Create lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
  notify: Start-nginx
